### ISSUE TITLE
Nov Open Data updates

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#820]
## Monthly Notifications:
- [x] Send Zoning reminder email (Run *Monthly_Zoning_Notification_Email.py* -or- use email template) 
- [x] Send TRD reminder email - (Run *Monthly_TRD_Notification_Email.py* -or- use email template) 

## Monthly Datasets

- [x] **Zoning & Sidewalk Cafe features [fgdb/shp]** & **Georeferenced NYC Zoning Maps [fgdb]** 
  - [x] Run Zoning NYSP Dissolve
  - [x] Process Files - Run  *Zoning and Sidewalk Cafe* tool (update metadata, package files for webteam)
  - [x] Manually copy current month's zoning folder from C/temp to BytesProduction folder
  - [x] Manually generate metadata pdfs
  - [x] Check to see if any zoning map changes are in BX CD10 or Staten Island **(If yes, need to run LDGMA)**
  - [x] Update Open Data log
  - [x] Upload zoning files to Digital Ocean for Carto Syncs/ZTLDB generation
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL - Run *ZoningAGO.py* and *_update_ini.py*
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following two steps need to be scheduled but can be run independently from previous steps**
  - [x] Pull data from TRD and update SDE PROD - Run *CopyZoning.py* (Check ini for SDE connection)
  - [x] Pull data from TRD and update SDE PROD - Run *CopyZoningGeoMaps* script for Zoning Maps only (Check ini for SDE connection)
-----

- [x] **Digital City Map (DCM) [shp/fgdb]**

  - [x] Pull data from TRD and update BytesProduction - Run *BP_DCM.py* script
  - [x] Manually generate metadata pdfs
  - [x] Update Open Data log
  - [x] Upload files to Digital Ocean for DE
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following step needs to be scheduled but can be run independently from previous steps**
  - [x] Pull data from TRD and update PROD SDE and M lyr meta - Run *SDE_DCM.py* script (Check ini for SDE connection)
-----

- [x] **E-Designation [shp/csv]**<sup id="a1"> [1](#f1)</sup>

  - [x] Receive automated email verifying new E-Designation file from Susan has been moved to M drive w/ appended "as of date" from the email and that both *EDes_GPull.py* and *EDes_Generation.py* script (creates shapefile) has been run. *This is currently automated*
        -This can be sent multiple times per month (uses latest one) 
  - [x] Distribute Files - Run  *EDes_BP_Distribution.py* script (update metadata, push files to BytesProduction, package files for webteam) 
  - [x] Manually generate metadata pdf
  - [x] Create web folder in BytesProduction and zip files for CSV and SHP
  - [x] Distribute Files - Run *EDes_SDE_Distribution.py* script (push to SDE PROD, update lyr metadata)
  - [x] Update Open Data log
  - [x] Upload files to Digital Ocean for Carto Syncs
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log 
  - [ ] Update The Guide card (optional)
-----

- [x] **Mandatory Inclusionary Housing (MIH) [shp]**<sup id="a2"> [2](#f2)</sup>

  - [x] Manually edit/create new mapped areas based on Appendix F changes from Paul Power
        -This can happen twice a month (check Stated Meeting Report) 
  - [x] Process Files - Run *BYTES_Distribution* script (update metadata, package files for webteam, push to BytesProduction)
  - [x] Manually generate metadata pdf
  - [x] Update Open Data log
  - [x] Upload files to Digital Ocean for Carto Syncs
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

  **The following needs to be scheduled but can be run independently from previous steps**
  - [x] Process Files - Run  *SDE_Distribution* script (push to SDE PROD, update lyr metadata, update & send MIH blocks to DOB) (Check ini for SDE connection)
----

- [x] **Zoning Tax Lot Database (ZTLDB) [csv]**

  - [x] Upload requisite data sets to DigitalOcean for DE to pick-up [Zoning Features & DOF/DTM Features]
  - [x] Run dataloading and build issues in github to generate ZTLDB
  - [x] Notify reviewer that ZTLDB is ready for QA
  - [x] Perform QA review of ZTLDB
  - [x] Updated Readme doc and create pdf
  - [x] Receive notification from reviewer that csv and readme are QA'd and ready
  - [x] Zip the csv and pdf readme
  - [x] Update Bytes (send email to Webteam)
  - [x] Update Open Data log 
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
----
- [x] **Zoning Application Portal (ZAP) [csv]**

  - [x] Pull Files from Digital Ocean - Run zap_pull.py
  - [x]  Manually update data dictionary (version/update date)
  - [x]  Run zap_package.py
  - [x]  Manually copy files to M:\GIS\DATA\ZAP (ensure to select read-only in properties)
  - [x]  Update Open Data log
  - [x]  Update Bytes (send email to Webteam)
  - [x]  Send email to Open Data team (after confirmation from webteam)
  - [x]  Update MMR log
  - [ ]  Update The Guide card (optional)
----

- [x] **MapPLUTO [shp/fgdb/csv]**

  - [x] Receive pluto.csv (corrections included) file from Data Engineering
  - [x] Receive notification from Lynn that raw_data files have been reviewed and are available. 
  - [x] Receive and review Data dictionary, Readme and PLUTOChangeReadme
  - [x] Generate Files - Run *MapPLUTO_BP* script (package files for webteam, moves to Bytes Production)
  - [x] Distribute Files - Run *MapPLUTO_Distribute* script (push to PROD and ARCHIVE SDEs, updates lyr metadata [MapPLUTO / Archive MapPLUTO / Borough MapPLUTO], creates AGO feature class on PROD) (Check ini for SDE connection)
  - [x] Manually generate metadata fgdb pdf
  - [x] Update Open Data log
  - [x] Upload to Digital Ocean for DE
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)
----

- [ ] **Lower Density Growth Management Area (LDGMA) [shp]**<sup id="a3"> [3](#f3)</sup>

  - [ ] Check Zoning Districts for changes in SI/BX10 for month
  - [ ] Generate LDGMA File - Run  *LDGMA_Distribution* script (update metadata, package files for webteam, push to SDE PROD, update lyr metadata)
  _Update script - separate file generation from SDE/lyr meta update (potential for new script for all monthly SDE/lyr meta updates_
  - [ ] Update Open Data log
  - [ ] Upload files to Digital Ocean for DE
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)

## Quarterly Datasets

- [x] **LION & Districts (22C) [shp/fgdb]**

  - [x] Receive notification from GRU that GSS LION toolbox script has been run and files available for web team
  - [x] Schedule CopyDistricts.py to distribute LION and Districts files across SDE (Check ini for SDE connection)
  - [x] Receive notification from Web team that all LION and Districts related data sets have been posted to BYTES
  - [x] Run LION/Districts archive script to archive old version on SDE Archive
  - [x] Update Open Data log
  - [x] Upload files to Digital Ocean for DE
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [x] **Pseudo Lots (22C) [shp]**
  - [x] Receive notification from GRU that Pseudo Lots shapefile is available
  - [x] Update and print metadata
  - [x] Package/zip files
  - [x] Distribute files to SDE
  - [x] Update Open Data log
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

## Biannual Datasets

- [x] **Housing Database [shp/fgdb/csv]**

  - [x] Receive notification from HED/DE that raw data is available
  - [x] Run process, package and distribute scripts
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Update Open Data log
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

## Non-Scheduled Datasets

- [x] **Capital Projects Database (CPDB) [shp/csv]**

  - [x] Confirm DO latest folder contains correct version
  - [x] Run CPDB Bytes Production Distribution Script
  - [x] Update Data Dictionary and Readme
  - [x] Run CPDB SDE Distribution Script
  - [x] Update Open Data Log
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
----
- [ ] **Facilities (FacDB) [shp/fgdb/csv]**

  - [ ] Update data and package zips in BytesProduction
  - [ ] Manually distribute to SDE PROD
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean for DE 
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **Waterfront Property Access Areas (WPAA) [shp/fgdb]**

  - [ ] Update M: drive directory to include these files
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean for DE
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **City Owned & Leased Properties (COLP) [shp/fgdb/csv/xlsx]**

  - [ ] Update M: drive directory to include these files
  - [ ] Update Open Data log
  - [ ] Update SDE PROD (manually)
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [ ] **Privately-Owned Public Spaces (POPS) [shp/csv]**

  - [ ] Update M: drive directory to include these files
  - [ ] Update Open Data log
  - [ ] Update Bytes (send email to Webteam)
  - [ ] Update AGOL
  - [ ] Upload files to Digital Ocean for DE
  - [ ] Send email to Open Data team (after confirmation from webteam)
  - [ ] Update MMR log
  - [ ] Update The Guide card (optional)
----
- [x] **FRESH [shp]**

  - [x] Receive updated source files (Zoning incentive from DCP Housing and/or Tax incentive from EDC)
  - [x] Process files to generate new shapefile (Union the Zoning & Tax incentive areas)
  - [x] Update and print metadata
  - [x] Package/zip files
  - [x] Distribute files to SDE
  - [x] Update Open Data log
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Upload files to Digital Ocean
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log
  - [ ] Update The Guide card (optional)

## Footnotes
<b id="f1">1:</b> If EARD provides designations for month. [↩](#a1)
<b id="f2">2:</b> If MIH issued by City Council for month. [↩](#a2)
<b id="f3">3:</b> If Zoning District changes in SI/BX10 for month. [↩](#a3)
**\*** clicking icons will navigate user back to original line of footnote

**Comment by croswell81** [comment]
PLUTO 22v2 to AGOL script throwing errors. Had to run manually. See errors below:

C:\Python27\ArcGIS10.6\python.exe G:/ScheduleTasks/PublishToAGOL/PyScripts/_update_ini.py
G:\ScheduleTasks\PublishToAGOL\_MapPluto\mappluto.mxd
G:\Connections\arcsdegis\sde@GISPROD.sde\GISPROD.SDE.MapPLUTO
856998: maxRecordCount
creating xml file for MAPPLUTO
Starting Feature Service publish process
{'q': 'title:"MAPPLUTO"AND owner:"DCP_GIS" AND type:"Feature Service"', 'token': u'SbeuCz1actxhQKYESnBHZWKRONZrSRaMUrGOWqgrtqw6FiD8dELXuY2EpBH4AdQsRkaWTs3indUscQjfP-Ufd6CldGk75Nt3LkfHLp6VYLEBG4TMo09uxdH-6Ml9a0h8Oe4VtcnoKR0djpPhb-LjlFoRyr0jCyDq51xhfU5CqnZumg-zaaip0Qf8Cua6Yq80', 'f': 'json'}
{u'nextStart': -1, u'start': 1, u'total': 1, u'num': 10, u'results': [{u'avgRating': 0, u'proxyFilter': None, u'culture': u'en-us', u'lastViewed': 1670022000000L, u'owner': u'DCP_GIS', u'guid': None, u'screenshots': [], u'id': u'1564ace0b4f44318ac39920737f9bd07', u'size': -1, u'appCategories': [], u'access': u'public', u'languages': [], u'title': u'MAPPLUTO', u'groupDesignations': None, u'numRatings': 0, u'advancedSettings': None, u'snippet': u'MapPLUTO was created by the Department of City Planning to meet the growing need for extensive land use at the tax lot level in PC mapping format.', u'listed': False, u'largeThumbnail': None, u'type': u'Feature Service', u'thumbnail': u'thumbnail/thumbnail.png', u'industries': [], u'numViews': 52037, u'description': u"This dataset represents a compilation of data from various government agencies throughout the City of New York. The underlying geography is derived from the Tax Lot Polygon feature class which is part of the Department of Finance's Digital Tax Map (DTM). The tax lots have been clipped to the shoreline, as defined by NYCMap planimetric features. The attribute information is from the Department of City Planning's PLUTO data. The attribute data pertains to tax lot and building characteristics and geographic, political and administrative information for each tax lot in New York City. The Tax Lot Polygon feature class and PLUTO are derived from different sources. As a result, some PLUTO records did not have a corresponding tax lot in the Tax Lot polygon feature class at the time of release. These records are included in a separate non-geographic PLUTO Only DBase (*.dbf) table. There are a number of reasons why there can be a tax lot in PLUTO that does not match the DTM; the most common reason is that the various source files are maintained by different departments and divisions with varying update cycles and criteria for adding and removing records. The attribute definitions for the PLUTO Only table are the same as those for MapPLUTO. DCP Mapping Lots includes some features that are not on the tax maps. They have been added by DCP for cartographic purposes. They include street center 'malls', traffic islands and some built streets through parks. These features have very few associated attributes.", u'tags': [u' \tQueens', u' PLUTO', u' Tax Lot', u' Brooklyn', u' New York City', u' Boundaries', u' Manhattan', u' MapPLUTO', u' Staten Island', u' Bronx', u' Parcels', u' DTM', u' New York'], u'numComments': 0, u'typeKeywords': [u'ArcGIS Server', u'Data', u'Feature Access', u'Feature Service', u'Metadata', u'Service', u'Singlelayer', u'Hosted Service'], u'extent': [[-74.25732725864636, 40.495800782770544], [-73.69938540598433, 40.915485005575526]], u'contentStatus': u'public_authoritative', u'subInfo': 0, u'scoreCompleteness': 83, u'banner': None, u'properties': None, u'categories': [], u'name': u'MAPPLUTO', u'licenseInfo': u'<DIV STYLE="text-align:Left;"><DIV><DIV><P><SPAN>MapPLUTO is being provided by the Department of City Planning (DCP) on DCP\'s website for informational purposes only. DCP does not warranty the completeness, accuracy, content, or fitness for any particular purpose or use of MapPLUTO, nor are any such warranties to be implied or inferred with respect to MapPLUTO as furnished on the website. DCP and the City are not liable for any deficiencies in the completeness, accuracy, content, or fitness for any particular purpose or use of MapPLUTO, or applications utilizing MapPLUTO, provided by any third party.</SPAN></P></DIV></DIV></DIV>', u'created': 1463686713000L, u'url': u'https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/MAPPLUTO/FeatureServer', u'documentation': None, u'modified': 1660312331000L, u'isOrgItem': True, u'spatialReference': u'102718', u'protected': True, u'orgId': u'GfwWNkhOj9bNBqoJ', u'ownerFolder': None, u'accessInformation': u'NYC Department of City Planning, Information Technology Division'}]}
found Feature Service : 1564ace0b4f44318ac39920737f9bd07
{'q': 'title:"MAPPLUTO"AND owner:"DCP_GIS" AND type:"Service Definition"', 'token': u'SbeuCz1actxhQKYESnBHZWKRONZrSRaMUrGOWqgrtqw6FiD8dELXuY2EpBH4AdQsRkaWTs3indUscQjfP-Ufd6CldGk75Nt3LkfHLp6VYLEBG4TMo09uxdH-6Ml9a0h8Oe4VtcnoKR0djpPhb-LjlFoRyr0jCyDq51xhfU5CqnZumg-zaaip0Qf8Cua6Yq80', 'f': 'json'}
{u'nextStart': -1, u'start': 1, u'total': 1, u'num': 10, u'results': [{u'avgRating': 0, u'proxyFilter': None, u'culture': u'en-us', u'lastViewed': -1, u'owner': u'DCP_GIS', u'guid': u'D21D17FC-B1A7-4FEB-AD3E-90B14AB70D46', u'screenshots': [], u'id': u'7d6d3bf6f7f249bb82f800bf13325a8f', u'size': -1, u'appCategories': [], u'access': u'private', u'languages': [], u'title': u'MAPPLUTO', u'groupDesignations': None, u'numRatings': 0, u'advancedSettings': None, u'snippet': u'MapPLUTO was created by the Department of City Planning to meet the growing need for extensive land use at the tax lot level in PC mapping format.', u'listed': False, u'largeThumbnail': None, u'type': u'Service Definition', u'thumbnail': u'thumbnail/thumbnail.png', u'industries': [], u'numViews': 27, u'description': u"This dataset represents a compilation of data from various government agencies throughout the City of New York. The underlying geography is derived from the Tax Lot Polygon feature class which is part of the Department of Finance's Digital Tax Map (DTM). The tax lots have been clipped to the shoreline, as defined by NYCMap planimetric features. The attribute information is from the Department of City Planning's PLUTO data. The attribute data pertains to tax lot and building characteristics and geographic, political and administrative information for each tax lot in New York City. The Tax Lot Polygon feature class and PLUTO are derived from different sources. As a result, some PLUTO records did not have a corresponding tax lot in the Tax Lot polygon feature class at the time of release. These records are included in a separate non-geographic PLUTO Only DBase (*.dbf) table. There are a number of reasons why there can be a tax lot in PLUTO that does not match the DTM; the most common reason is that the various source files are maintained by different departments and divisions with varying update cycles and criteria for adding and removing records. The attribute definitions for the PLUTO Only table are the same as those for MapPLUTO. DCP Mapping Lots includes some features that are not on the tax maps. They have been added by DCP for cartographic purposes. They include street center 'malls', traffic islands and some built streets through parks. These features have very few associated attributes.", u'tags': [u' \tQueens', u' PLUTO', u' Tax Lot', u' Brooklyn', u' New York City', u' Boundaries', u' Manhattan', u' MapPLUTO', u' Staten Island', u' Bronx', u' Parcels', u' DTM', u' New York'], u'numComments': 0, u'typeKeywords': [u'.sd', u'ArcGIS', u'Metadata', u'SDE Feature Class', u'Service Definition', u'Online'], u'extent': [[-74.2573257172533, 40.4957925584428], [-73.6993840435391, 40.9154767119154]], u'subInfo': 0, u'scoreCompleteness': 66, u'banner': None, u'properties': None, u'categories': [], u'name': u'MAPPLUTO.sd', u'licenseInfo': u'', u'created': 1456339781000L, u'url': u'', u'documentation': None, u'modified': 1660312327000L, u'isOrgItem': True, u'spatialReference': u'NAD_1983_StatePlane_New_York_Long_Island_FIPS_3104_Feet', u'protected': False, u'ownerFolder': None, u'accessInformation': u'NYC Department of City Planning, Information Technology Division'}]}
found Service Definition : 7d6d3bf6f7f249bb82f800bf13325a8f
mappingMXD.tags: Queens, PLUTO, Tax Lot, Brooklyn, New York City, Boundaries, Manhattan, MapPLUTO, Staten Island, Bronx, Parcels, DTM, New York
IOError on save, do you have the MXD open? Summary/tag info not pushed to MXD, publishing may fail.
Created G:\ScheduleTasks\PublishToAGOL\PyScripts\tempDir\MAPPLUTO.sd
updated SD:   7d6d3bf6f7f249bb82f800bf13325a8f
https://www.arcgis.com/sharing/rest/content/users/DCP_GIS/publish
Traceback (most recent call last):
  File "G:/ScheduleTasks/PublishToAGOL/PyScripts/_update_ini.py", line 83, in <module>
{u'services': [{u'success': False}]}
successfully updated...[{u'success': False}]...
    execfile(updatePy)
  File "G:\ScheduleTasks\PublishToAGOL\PyScripts\update.py", line 507, in <module>
    fsID = agol.publish()
  File "G:\ScheduleTasks\PublishToAGOL\PyScripts\update.py", line 219, in publish
    return jsonResponse['services'][0]['serviceItemId']
KeyError: 'serviceItemId'

Process finished with exit code 1
